# Generated by Django 3.2.2 on 2021-05-07 14:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Druh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oznaceni_druhu', models.CharField(help_text='Zadejte text o maximální délce 50 znaků; text musí být jedinečný', max_length=50, unique=True, verbose_name='Označení druhu zboží')),
                ('kategorie', models.CharField(blank=True, choices=[('traktory', 'Traktory'), ('sklízecí mlátičky', 'Sklízecí mlátičky'), ('sklízecí řezačky', 'Sklízecí řezačky'), ('postřikovače', 'Postřikovače'), ('setí a hnojení', 'Setí a hnojení'), ('zpracování půdy', 'Zpracování půdy'), ('manipulační technika', 'Manipulační technika'), ('krmné vozy', 'Krmné vozy'), ('sklizen pice', 'Sklizen pice')], default='elektro', help_text='Vyberte kategorie', max_length=20, verbose_name='kategorie')),
            ],
            options={
                'verbose_name': 'Druh zboží',
                'verbose_name_plural': 'Druh zboží',
                'ordering': ['oznaceni_druhu'],
            },
        ),
        migrations.CreateModel(
            name='Stroj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(help_text='Zadejte text o maximální délce 100 znaků', max_length=100, verbose_name='Název zboží')),
                ('popis', models.TextField(blank=True, null=True, verbose_name='Popis zboží')),
                ('cena', models.FloatField(help_text='Zadejte nezáporné desetinné číslo', null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Cena')),
                ('stav', models.IntegerField(blank=True, choices=[(5, 'nový'), (4, 'málo použitý'), (3, 'použitý'), (2, 'hodně použitý'), (1, 'nefunkční')], default=3, help_text='Vyberte označení stavu', max_length=1, verbose_name='Stav stroje')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='stroj/%Y/%m/%d/', verbose_name='Fotka stroje')),
                ('druh', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='stranka.druh')),
            ],
            options={
                'verbose_name': 'Stroj',
                'verbose_name_plural': 'Stroj',
                'ordering': ['-cena', 'nazev'],
            },
        ),
    ]
