# Generated by Django 3.2.2 on 2021-05-07 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stranka', '0003_alter_kategorie_oznaceni_druhu'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kategorie',
            options={'ordering': ['oznaceni_druhu'], 'verbose_name': 'Typ stroje', 'verbose_name_plural': 'Typ stroje'},
        ),
        migrations.AlterField(
            model_name='stroj',
            name='nazev',
            field=models.CharField(help_text='Zadejte text o maximální délce 100 znaků', max_length=100, verbose_name='Název stroje'),
        ),
        migrations.AlterField(
            model_name='stroj',
            name='popis',
            field=models.TextField(blank=True, null=True, verbose_name='Popis stroje'),
        ),
    ]
